"""Bind predicted frames to only the actual states generated by their executed prefix."""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path

import h5py
import numpy as np


@dataclass
class AlignmentPair:
    episode_id: str
    request_id: str
    origin_step: int
    action_sequence_hash: str
    prediction_offset_time: float
    actual_control_step: int
    actual_sim_time: float
    camera_id: str
    preprocessing_version: str
    predicted: np.ndarray
    actual: np.ndarray | None
    valid: bool
    invalid_reason: str
    synthetic: bool


def pairs_from_episode(path: Path):
    pairs = []
    with h5py.File(path, "r") as f:
        episode = json.loads(f.attrs["metadata_json"])
        for request_id, request in f["requests"].items():
            if "prediction/rgb" not in request:
                continue  # Missing predictions remain unavailable; no blank frames are created.
            metadata = json.loads(request.attrs["metadata_json"])
            specification = metadata["prediction_spec"] or {}
            predicted_preprocessing = specification.get("preprocessing_version", "UNKNOWN")
            actual_preprocessing = episode["env_specs"].get("preprocessing_version", "UNKNOWN")
            offsets = request["prediction/offset_steps"][:]
            times = request["prediction/offset_times"][:]
            mask = request["prediction/valid"][:]
            reasons = request["prediction/invalid_reason"].asstr()[:]
            for camera, frames in request["prediction/rgb"].items():
                actual_key = f"obs/sensor_data/{camera}/rgb"
                for index, (offset, dt) in enumerate(zip(offsets, times, strict=True)):
                    step = int(metadata["origin_step"] + offset)
                    reason = reasons[index]
                    actual = None
                    if actual_key not in f:
                        reason = "camera_unavailable"
                    elif step >= len(f[actual_key]):
                        reason = "outside_episode"
                    else:
                        actual = f[actual_key][step]
                        if actual.shape != frames[index].shape:
                            reason = "camera_shape_mismatch"
                        elif predicted_preprocessing != actual_preprocessing or actual_preprocessing == "UNKNOWN":
                            reason = "preprocessing_mismatch"
                    valid = bool(mask[index]) and reason == "valid"
                    pairs.append(AlignmentPair(
                        episode["episode_id"], request_id, metadata["origin_step"],
                        metadata["action_sequence_hash"], float(dt), step, step * episode["env_specs"]["dt_sim"],
                        camera, actual_preprocessing, frames[index], actual, valid, reason,
                        bool(episode["synthetic"] or metadata["synthetic"])))
    return pairs
